import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
PAPER = ROOT / "paper"
PAPER.mkdir(exist_ok=True)


def read_csv(name):
    with (RESULTS / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def tex_escape(value):
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def fnum(value, digits=3):
    return f"{float(value):.{digits}f}"


def write_row_counts(summary):
    rows = summary["row_counts"]
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Persisted evidence artifacts generated by the v5 protocol.}",
        r"\label{tab:row-counts}",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"Artifact & Rows \\",
        r"\midrule",
    ]
    for key, value in rows.items():
        lines.append(f"{tex_escape(key.replace('_', ' '))} & {value:,} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    (PAPER / "generated_row_counts.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_gate_table(summary):
    metrics = summary["metrics"]
    gates = summary["gates"]
    rows = [
        ("Hard success margin", r"$\geq 0.030$", metrics["success_margin_vs_strongest"], gates["hard_success_gate"]),
        ("Hard utility margin", r"$\geq 0.050$", metrics["utility_margin_vs_strongest"], gates["hard_utility_gate"]),
        ("Mechanism recall delta", r"$\geq 0.050$ or false-negative $\leq -0.030$", metrics["mechanism_recall_delta_vs_strongest"], gates["diagnostic_gate"]),
        ("Coverage false-negative delta", r"$\leq -0.030$ alternative", metrics["coverage_false_negative_delta_vs_strongest"], gates["diagnostic_gate"]),
        ("Tail failure delta", r"$\leq 0$", metrics["tail_mechanism_failure_delta_vs_strongest"], gates["non_regression_gate"]),
        ("Unsafe deployment delta", r"$\leq 0$", metrics["unsafe_deployment_failure_delta_vs_strongest"], gates["non_regression_gate"]),
        ("Redundancy delta", r"$\leq 0$", metrics["redundancy_rate_delta_vs_strongest"], gates["non_regression_gate"]),
        ("Selection cost delta", r"$\leq 0$", metrics["selection_cost_delta_vs_strongest"], gates["non_regression_gate"]),
        ("Annotation burden delta", r"$\leq 0$", metrics["annotation_burden_delta_vs_strongest"], gates["non_regression_gate"]),
        ("Paired hard utility wins", r"$\geq 8/10$", metrics["paired_hard_utility_wins"], gates["paired_hard_gate"]),
        ("Ablation success margin", r"$\geq 0.010$ or utility $\geq 0.040$", metrics["ablation_success_margin_vs_best_removed"], gates["ablation_gate"]),
        ("Stress endpoint utility margin", r"$\geq 0.050$", metrics["stress_endpoint_utility_margin"], gates["stress_endpoint_gate"]),
        ("Strict fixed-risk coverage", r"$0.300 \leq$ coverage $< 0.950$", metrics["strict_fixed_risk_coverage"], gates["fixed_risk_gate"]),
        ("Strict fixed-risk utility margin", r"$> 0$", metrics["strict_fixed_risk_utility_margin"], gates["fixed_risk_gate"]),
    ]
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Frozen v5 local gates. The scope gate is separate and fails because no real public-dataset/downstream-policy validation is present.}",
        r"\label{tab:gates}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{llrl}",
        r"\toprule",
        r"Gate quantity & Frozen criterion & Value & Result \\",
        r"\midrule",
    ]
    for name, criterion, value, passed in rows:
        shown = f"{float(value):.5f}" if isinstance(value, (float, int)) else str(value)
        lines.append(f"{tex_escape(name)} & {criterion} & {shown} & {'PASS' if passed else 'FAIL'} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"}", r"\end{table}"])
    (PAPER / "generated_gate_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_failure_cases():
    cases = read_csv("failure_cases.csv")
    def path_token(value):
        safe = str(value).replace("\\", "/").replace("{", "").replace("}", "")
        return rf"\path{{{safe}}}"

    lines = [
        r"\begin{table}[p]",
        r"\centering",
        r"\caption{Failure cases retained in the v5 audit. These are not hidden; they define the external validation agenda.}",
        r"\label{tab:failure-cases}",
        r"\scriptsize",
        r"\begin{tabularx}{\linewidth}{p{0.17\linewidth}p{0.17\linewidth}X X}",
        r"\toprule",
        r"Case & Split & Observed failure & Lesson \\",
        r"\midrule",
    ]
    for row in cases:
        lines.append(
            f"{path_token(row['case'])} & {path_token(row['stress_split'])} & "
            f"{tex_escape(row['observed_failure'])} & {tex_escape(row['lesson'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabularx}", r"\end{table}"])
    (PAPER / "generated_failure_cases.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_catalog_table():
    anchors = [
        ("RoboNet", "multi-robot visual foresight and shared manipulation data", "cross-robot scale does not guarantee force/tactile or recovery coverage"),
        ("BridgeData V2", "large-scale manipulation dataset", "mobile/tabletop diversity can still hide mechanism tails"),
        ("Open X-Embodiment / RT-X", "cross-embodiment robot data mixture", "embodiment scale creates schema-alignment pressure"),
        ("DROID", "in-the-wild robot manipulation data", "real-world breadth raises provenance and label-quality questions"),
        ("robomimic", "offline imitation benchmark suite", "benchmark cleanliness can underrepresent messy public-catalog tails"),
        ("RH20T", "teleoperation-rich robot demonstrations", "teleoperation provenance affects failure/recovery coverage"),
        ("LIBERO", "lifelong/instruction manipulation benchmark", "instruction coverage is not equivalent to mechanism coverage"),
        ("RoboCasa", "household/kitchen manipulation simulation benchmark", "simulated diversity needs contact/safety mechanism audits"),
    ]
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Catalog anchors used to pressure the local audit. They provide source context, not proof that the v5 experiment downloaded or trained on those datasets.}",
        r"\label{tab:catalog-anchors}",
        r"\small",
        r"\begin{tabularx}{\linewidth}{p{0.18\linewidth}p{0.32\linewidth}X}",
        r"\toprule",
        r"Anchor & Public role & Mechanism-coverage pressure \\",
        r"\midrule",
    ]
    for anchor, role, pressure in anchors:
        lines.append(f"{tex_escape(anchor)} & {tex_escape(role)} & {tex_escape(pressure)} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabularx}", r"\end{table}"])
    (PAPER / "generated_catalog_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_references():
    bib = r"""
@inproceedings{dasari2019robonet,
  title={RoboNet: Large-scale multi-robot learning},
  author={Dasari, Sudeep and Ebert, Frederik and Tian, Stephen and Nair, Suraj and Bucher, Bernadette and Schmeckpeper, Karl and Singh, Siddharth and Levine, Sergey and Finn, Chelsea},
  booktitle={Conference on Robot Learning},
  year={2019}
}

@article{walke2023bridgedata,
  title={BridgeData V2: A dataset for robot learning at scale},
  author={Walke, Homer and Black, Kevin and Lee, Abraham and Kim, Moo Jin and Du, Max and Zheng, Chongyi and Zhao, Tony Z. and Hansen-Estruch, Philippe and Vuong, Quan and He, Andre and others},
  journal={arXiv preprint arXiv:2308.12952},
  year={2023}
}

@article{openx2023,
  title={Open X-Embodiment: Robotic Learning Datasets and RT-X Models},
  author={{Open X-Embodiment Collaboration}},
  journal={arXiv preprint arXiv:2310.08864},
  year={2023}
}

@article{khazatsky2024droid,
  title={DROID: A Large-Scale In-the-Wild Robot Manipulation Dataset},
  author={Khazatsky, Alexander and others},
  journal={arXiv preprint arXiv:2403.12945},
  year={2024}
}

@article{octo2024,
  title={Octo: An Open-Source Generalist Robot Policy},
  author={{Octo Model Team} and others},
  journal={arXiv preprint arXiv:2405.12213},
  year={2024}
}

@inproceedings{mandlekar2021robomimic,
  title={What Matters in Learning from Offline Human Demonstrations for Robot Manipulation},
  author={Mandlekar, Ajay and Xu, Danfei and Wong, Josiah and Nasiriany, Soroush and Wang, Chen and Kulkarni, Rohun and Fei-Fei, Li and Savarese, Silvio and Zhu, Yuke and Martin-Martin, Roberto},
  booktitle={Conference on Robot Learning},
  year={2021}
}

@article{liu2023libero,
  title={LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning},
  author={Liu, Bo and Zhu, Yifeng and Gao, Chongkai and Feng, Yihao and Liu, Qiang and Zhu, Yuke and Stone, Peter},
  journal={arXiv preprint arXiv:2306.03310},
  year={2023}
}

@article{robocasa2024,
  title={RoboCasa: Large-Scale Simulation of Everyday Tasks for Generalist Robots},
  author={Nasiriany, Soroush and others},
  journal={arXiv preprint arXiv:2406.02523},
  year={2024}
}

@article{fang2023rh20t,
  title={RH20T: A Comprehensive Robotic Dataset for Learning Diverse Skills in One-Shot},
  author={Fang, Hao-Shu and others},
  journal={arXiv preprint arXiv:2307.00595},
  year={2023}
}

@article{settles2009active,
  title={Active Learning Literature Survey},
  author={Settles, Burr},
  journal={University of Wisconsin-Madison Department of Computer Sciences},
  year={2009}
}

@inproceedings{sener2018coreset,
  title={Active Learning for Convolutional Neural Networks: A Core-Set Approach},
  author={Sener, Ozan and Savarese, Silvio},
  booktitle={International Conference on Learning Representations},
  year={2018}
}

@article{nemhauser1978submodular,
  title={An analysis of approximations for maximizing submodular set functions},
  author={Nemhauser, George L. and Wolsey, Laurence A. and Fisher, Marshall L.},
  journal={Mathematical Programming},
  volume={14},
  number={1},
  pages={265--294},
  year={1978}
}

@article{krause2014submodular,
  title={Submodular Function Maximization},
  author={Krause, Andreas and Golovin, Daniel},
  journal={Tractability},
  pages={71--104},
  year={2014}
}

@article{jain2013coverage,
  title={Learning Trajectory Preferences for Manipulators via Iterative Improvement},
  author={Jain, Ashesh and Sharma, Shikhar and Joachims, Thorsten and Saxena, Ashutosh},
  journal={Advances in Neural Information Processing Systems},
  year={2013}
}

@article{levine2018learning,
  title={Learning Hand-Eye Coordination for Robotic Grasping with Deep Learning and Large-Scale Data Collection},
  author={Levine, Sergey and Pastor, Peter and Krizhevsky, Alex and Ibarz, Julian and Quillen, Deirdre},
  journal={International Journal of Robotics Research},
  year={2018}
}
"""
    (PAPER / "references.bib").write_text(bib.strip() + "\n", encoding="utf-8")


def write_main(summary):
    metrics = summary["metrics"]
    replacements = {
        "@@PROP_SUCCESS@@": fnum(metrics["proposed_success"], 5),
        "@@BASE_SUCCESS@@": fnum(metrics["baseline_success"], 5),
        "@@PROP_UTILITY@@": fnum(metrics["proposed_utility"], 5),
        "@@BASE_UTILITY@@": fnum(metrics["baseline_utility"], 5),
        "@@SUCCESS_MARGIN@@": fnum(metrics["success_margin_vs_strongest"], 5),
        "@@UTILITY_MARGIN@@": fnum(metrics["utility_margin_vs_strongest"], 5),
        "@@RECALL_DELTA@@": fnum(metrics["mechanism_recall_delta_vs_strongest"], 5),
        "@@FALSE_NEG_DELTA@@": fnum(metrics["coverage_false_negative_delta_vs_strongest"], 5),
        "@@TAIL_DELTA@@": fnum(metrics["tail_mechanism_failure_delta_vs_strongest"], 5),
        "@@UNSAFE_DELTA@@": fnum(metrics["unsafe_deployment_failure_delta_vs_strongest"], 5),
        "@@REDUND_DELTA@@": fnum(metrics["redundancy_rate_delta_vs_strongest"], 5),
        "@@COST_DELTA@@": fnum(metrics["selection_cost_delta_vs_strongest"], 5),
        "@@BURDEN_DELTA@@": fnum(metrics["annotation_burden_delta_vs_strongest"], 5),
        "@@ABLAT_SUCCESS@@": fnum(metrics["ablation_success_margin_vs_best_removed"], 5),
        "@@ABLAT_UTILITY@@": fnum(metrics["ablation_utility_margin_vs_best_removed"], 5),
        "@@STRESS_MARGIN@@": fnum(metrics["stress_endpoint_utility_margin"], 5),
        "@@FIXED_COVER@@": fnum(metrics["strict_fixed_risk_coverage"], 5),
        "@@FIXED_MARGIN@@": fnum(metrics["strict_fixed_risk_utility_margin"], 5),
        "@@PAIRED_WINS@@": str(metrics["paired_hard_utility_wins"]),
        "@@PAIRED_TOTAL@@": str(metrics["paired_hard_utility_total"]),
        "@@STRICT_BUDGET@@": fnum(summary["strict_budget"], 3),
        "@@BASELINE@@": tex_escape(summary["strongest_non_oracle_baseline"]),
    }
    tex = r"""
\documentclass{article}
\usepackage{iclr2026_conference,times}
\input{math_commands.tex}
\usepackage{hyperref}
\usepackage{url}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{microtype}
\usepackage{xcolor}
\usepackage{tabularx}
\usepackage{array}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{enumitem}
\hypersetup{
  colorlinks=false,
  citebordercolor={0 0.85 0.20},
  linkbordercolor={1 0.55 0},
  urlbordercolor={0 0.45 1},
  pdfborder={0 0 1.5}
}
\title{Mechanism-Coverage Audits for Open Robot Data}
\author{Anonymous Authors}
\raggedbottom

\newcommand{\method}{\textsc{MCG-Audit-v5}}
\newcommand{\vfour}{\textsc{MCG-Audit-v4}}
\newcommand{\oracle}{\textsc{Oracle-M}}
\newcommand{\todoexternal}{\textbf{Scope gate failed}}

\begin{document}
\maketitle

\begin{abstract}
Open robot data is usually summarized by scale: trajectories, tasks, embodiments, policies, and scenes. Scale is valuable, but scale can hide mechanism gaps. A public catalog can contain many demonstrations while still undersampling contact transitions, force/tactile cues, recovery after failure, deformable interaction, irreversible side effects, long-horizon dependencies, schema incompatibilities, provenance ambiguity, and label uncertainty. We rebuild Paper 111 around a stricter claim: mechanism-level coverage should predict downstream failure better than coarse catalog counts and should improve data selection without increasing tail risk or annotation burden. The v5 audit evaluates 8 catalog-style public robot data families, 10 mechanism-gap regimes, 8 deployment splits, 16 selectors, and 10 paired seeds, generating 102,400 main cells, 8,000 ablation cells, 48,000 stress cells, and 51,200 fixed-risk cells. On the hard aggregate, \method{} reaches success @@PROP_SUCCESS@@ and utility @@PROP_UTILITY@@ versus @@BASE_SUCCESS@@ and @@BASE_UTILITY@@ for the strongest non-oracle baseline, \texttt{@@BASELINE@@}. It improves mechanism recall by @@RECALL_DELTA@@, lowers false coverage by @@FALSE_NEG_DELTA@@, lowers tail failure by @@TAIL_DELTA@@, and wins @@PAIRED_WINS@@/@@PAIRED_TOTAL@@ paired hard-split seeds. The terminal decision is \textbf{STRONG\_REVISE}: all frozen local gates pass, but the paper is not ICLR-main-ready because no real public dataset annotation, downstream trained-policy evaluation, deployment log, or rollout-video evidence is present.
\end{abstract}

\section{Motivation}
Robot learning has entered a data-scale era. RoboNet, BridgeData, Open X-Embodiment/RT-X, DROID, robomimic, RH20T, LIBERO, RoboCasa, Octo, and related efforts have made data sharing and cross-embodiment learning central to robotics \citep{dasari2019robonet,walke2023bridgedata,openx2023,khazatsky2024droid,mandlekar2021robomimic,fang2023rh20t,liu2023libero,robocasa2024,octo2024}. The community has become good at asking whether a dataset is large. It is less good at asking whether a dataset covers the mechanisms that make deployed robot policies fail.

This distinction matters because robot failures are often mechanistic rather than merely visual. A gripper can encounter a contact transition that was never labeled; a policy can see many mugs but no force-rich insertion; a dataset can include many successful demonstrations but no recoveries; a cross-embodiment mixture can have task names that look compatible while action and state schemas are not. A scale metric can therefore produce false comfort. The uncomfortable reviewer question is: ``Does more open data actually cover the physical mechanisms that fail at deployment?''

The answer in this version is intentionally bounded. We do not claim to have downloaded every public robot dataset, normalized all schemas, relabeled mechanisms, trained policies, and measured real deployment performance. That evidence would be required for an ICLR-main submission. Instead, this v5 rebuild asks whether the mechanism-coverage thesis survives a much harsher local/catalog audit than the v4.1 version: stronger baselines, more shifts, fixed-risk deployment budgets, ablations, stress tests, and explicit failure cases.

\paragraph{Contributions.}
First, we define mechanism coverage as a tensor over catalog family, embodiment, task, object class, sensor modality, mechanism, provenance, schema, and label quality. Second, we provide simple theory showing why trajectory/task/embodiment counts cannot identify mechanism coverage without mechanism labels. Third, we instantiate \method{}, a mechanism-coverage selector that trades off coverage gain, redundancy, provenance risk, schema mismatch, label uncertainty, and tail risk. Fourth, we evaluate a frozen v5 protocol against 15 comparators and report every predefined result, including non-perfect fixed-risk coverage and scope-gate failure.

\section{Problem Setting}
Let $\mathcal{D}=\{d_i\}_{i=1}^n$ denote a catalog of open robot data sources. A source may be a dataset, a benchmark suite, a teleoperation collection, or a simulation corpus. Each source exposes observed metadata $x_i$: counts, task names, embodiment names, modalities, license fields, and demonstration statistics. The unobserved object of interest is mechanism coverage over a set $\mathcal{M}$:
\[
  \begin{aligned}
  \mathcal{M}=\{&\text{contact},\text{force/tactile},\text{recovery},\text{deformable},\text{irreversible},\\
  &\text{long-horizon},\text{schema},\text{provenance},\text{label quality},\text{safety tail}\}.
  \end{aligned}
\]
For a selected subset $S\subseteq\mathcal{D}$, define $C_m(S)\in[0,1]$ as the covered mass for mechanism $m$. Coarse counts observe only $g(x_i)$, such as trajectories or tasks. They do not directly observe $C_m$.

The downstream deployment distribution is represented by contexts $z=(e,t,o,m,\sigma)$: embodiment, task, object class, mechanism, and shift. A selector $A$ maps catalog metadata and optional labels to a subset $S_A$. Its downstream utility is
\[
  \begin{aligned}
  U(A;z)=&\Pr[\text{success}\mid S_A,z] - \lambda_1 R_{\mathrm{tail}}(S_A,z)\\
  &-\lambda_2 R_{\mathrm{unsafe}}(S_A,z)-\lambda_3 B_{\mathrm{ann}}(S_A,z)\\
  &-\lambda_4 R_{\mathrm{schema}}(S_A,z).
  \end{aligned}
\]
We care about hard contexts where $m$ is rare, shifted, safety-critical, or schema-sensitive. The audit is not an end in itself; it is a guard against false coverage claims.

\subsection{False Coverage}
We define false coverage as the event that metadata implies coverage while a mechanism remains under-covered:
\[
  F_m(S)=\mathbb{1}\{g_m(S)\ge \tau_g \land C_m(S)<\tau_c\}.
\]
False coverage is worse than ignorance because it encourages a team to stop collecting data. In robotics this can be dangerous: a catalog may appear diverse while missing the precise contact/recovery mechanism needed for a deployment split.

\section{Theory}
\paragraph{Proposition 1: coarse-count non-identifiability.}
There exist two catalogs $\mathcal{D}$ and $\mathcal{D}'$ with identical trajectory counts, task counts, embodiment counts, and visual embedding diversity, but different mechanism coverage tensors $C(S)$ and $C'(S)$.

\textit{Proof sketch.}
Construct $\mathcal{D}$ and $\mathcal{D}'$ with the same number of demonstrations per task and embodiment. In $\mathcal{D}$, all demonstrations are successful pick-place trajectories with no recovery and no force/tactile annotations. In $\mathcal{D}'$, an equal number of demonstrations includes contact transitions, failed attempts, recoveries, and force/tactile events. Coarse counts and visual diversity can be matched by choosing objects and camera views identically. The mechanism coverage tensors differ on recovery and force/tactile axes. Therefore no function of those coarse counts alone identifies mechanism coverage. \hfill $\square$

\paragraph{Proposition 2: diminishing returns of mechanism coverage.}
If each selected data source contributes nonnegative coverage mass $w_{im}$ to mechanism $m$ and the mechanism utility is $h_m(c)=1-\exp(-\alpha_m c)$, then
\[
  f(S)=\sum_{m\in\mathcal{M}}\beta_m h_m\left(\sum_{i\in S}w_{im}\right)
\]
is monotone submodular. A greedy selector obtains the standard $(1-1/e)$ approximation for a cardinality budget \citep{nemhauser1978submodular,krause2014submodular}.

\textit{Interpretation.}
The result does not prove our particular simulator is real. It explains why a redundancy-aware mechanism selector is a plausible alternative to raw counts: once a mechanism is covered, additional near-duplicate demonstrations have diminishing returns.

\paragraph{Proposition 3: false-coverage risk bounds utility regret.}
Assume deployment loss decomposes as $\ell(z,S)=\ell_0(z)+\sum_m a_m(z)\max(0,\tau_m-C_m(S))+\epsilon$, with $a_m(z)\ge0$ and bounded $\epsilon$. If an audit has false-negative error $\eta_m=\Pr[F_m(S)]$, then expected regret relative to an oracle mechanism-labeled selector is bounded by
\[
  \mathbb{E}[\mathrm{Regret}(S)] \le \sum_m a_m \eta_m + \mathbb{E}[\epsilon] + \Delta_{\mathrm{approx}}.
\]
The bound is deliberately simple: reducing false coverage should reduce regret, but only if the mechanism labels are valid. If the labels are wrong or absent, the scope gate fails.

\paragraph{Negative theorem: catalog-only readiness is impossible.}
A catalog-only audit cannot certify downstream trained-policy performance when two datasets share identical metadata but differ in unobserved execution outcomes. This is a direct consequence of Proposition 1 with outcome labels hidden. Therefore this paper cannot be ICLR-main-ready without real policy evaluation, even when all local gates pass.

\section{Method}
\method{} scores candidate data sources by expected mechanism coverage gain minus penalties:
\[
  \begin{aligned}
  s_i =& \sum_m \beta_m \Delta C_m(i\mid S)
  - \gamma_1 \mathrm{Redundancy}(i,S)-\gamma_2 \mathrm{SchemaRisk}(i)\\
  &-\gamma_3 \mathrm{ProvenanceRisk}(i)-\gamma_4 \mathrm{LabelNoise}(i)
  -\gamma_5 \mathrm{TailRisk}(i).
  \end{aligned}
\]
The score is not intended as a universal recipe. It is a falsifiable audit scaffold. The selected subset should improve success and utility under hard shifts, but also reduce false negatives, tail mechanism failures, unsafe deployment failures, redundancy, selection cost, and annotation burden.

\paragraph{Mechanism taxonomy.}
The v5 taxonomy includes contact transitions, force/tactile cues, failure recovery, deformable interaction, irreversible side effects, long-horizon dependencies, embodiment schema, provenance/license consistency, label quality, and safety-tail reporting. These axes are chosen because they are plausible failure causes in robot learning and because coarse data scale does not identify them.

\paragraph{Coverage tensor.}
For each catalog family and regime, the audit constructs normalized pressure terms: contact pressure, force pressure, recovery pressure, deformable pressure, irreversible pressure, horizon pressure, schema pressure, provenance pressure, label pressure, and safety pressure. These terms are explicitly generated in \texttt{src/run\_experiment.py}. They are local stress variables, not claims of measured real-world dataset statistics.

\paragraph{Fixed-risk selection.}
The fixed-risk protocol freezes a risk score:
\[
  r=\mathrm{false\_negative}+0.75\,\mathrm{tail\_failure}+0.50\,\mathrm{unsafe\_failure}.
\]
Budgets are $0.062$, $0.066$, $0.070$, and $0.074$. The strictest budget is intentionally close to the v5 risk frontier, giving coverage @@FIXED_COVER@@ rather than a misleading value of 1.0.

\section{Experimental Protocol}
The protocol is deterministic, CPU-only, and generated by \texttt{src/run\_experiment.py}. It evaluates 8 catalog anchors, 10 regimes, 8 splits, 16 methods, and 10 seeds. Each cell represents 6 held-out local episodes. The row counts are large enough to support paired analysis while staying lightweight on RAM.

\input{generated_catalog_table.tex}

\paragraph{Catalog anchors.}
The anchors are public-dataset contexts from the robotics literature. They are used to pressure the audit design, not to claim that this run downloaded or trained on those datasets. This distinction is critical: cited datasets establish relevance, but external validation remains missing.

\paragraph{Regimes and splits.}
The ten regimes cover nominal metadata, contact-transition gaps, force/tactile gaps, recovery gaps, deformable gaps, irreversible side-effect gaps, long-horizon gaps, embodiment-schema gaps, provenance/label gaps, and combined catalog gaps. The eight splits are nominal catalog, task shift, object shift, embodiment shift, mechanism shift, sensor-modality shift, provenance/label shift, and heldout combined catalog gap.

\paragraph{Methods.}
The baselines include trajectory-count, task-count, embodiment-count, random-balanced, embedding-diversity, uncertainty sampling, failure-prediction selection, value-of-information active selection, dataset-card compliance selection, safety-event mining, label-quality-first selection, domain-mix robust selection, causal-feature coverage, the v4 mechanism-coverage audit, the v5 audit, and an oracle mechanism-labeled selector.

\paragraph{Frozen gates.}
The local decision is frozen in Table~\ref{tab:gates}. Passing local gates permits \textbf{STRONG\_REVISE}; it does not permit ICLR-main readiness. The external scope gate requires real public dataset annotation, label-quality checks, schema/provenance normalization, downstream trained policies, and deployment evidence.

\input{generated_gate_table.tex}
\input{generated_row_counts.tex}

\section{Hard-Aggregate Results}
\input{../results/hard_aggregate_table.tex}

The strongest non-oracle baseline is \texttt{@@BASELINE@@}. \method{} improves hard success by @@SUCCESS_MARGIN@@ and hard utility by @@UTILITY_MARGIN@@. It also improves mechanism recall by @@RECALL_DELTA@@ and lowers false coverage by @@FALSE_NEG_DELTA@@. The oracle remains above v5, with success and utility gaps that are large enough to matter. This is a healthy result: the audit helps, but it does not solve mechanism labeling.

\begin{figure}[t]
\centering
\includegraphics[width=0.96\linewidth]{../figures/coverage_gap_hard_utility_v5.png}
\caption{Hard-aggregate utility. The proposed v5 audit clears every non-oracle comparator but remains below the mechanism-labeled oracle.}
\label{fig:hard-utility}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=0.96\linewidth]{../figures/coverage_gap_diagnostics_v5.png}
\caption{Coverage diagnostics on the hard aggregate. The v5 audit improves recall while reducing false coverage, tail failure, schema mismatch, and label-noise risk relative to strong baselines.}
\label{fig:diagnostics}
\end{figure}

\input{../results/pairwise_decision_table.tex}

The paired hard-split test is deliberately seed-level. Against the strongest non-oracle baseline, \method{} wins @@PAIRED_WINS@@/@@PAIRED_TOTAL@@ paired seeds on utility. We report this rather than only aggregate means because a reviewer should be able to see whether the gain is carried by one lucky seed. It is not.

\section{Ablations}
\input{../results/ablation_table.tex}

The full v5 method beats the best removed-component ablation by @@ABLAT_SUCCESS@@ success and @@ABLAT_UTILITY@@ utility. The success margin clears the frozen ablation gate; the utility margin is just below the alternative $0.040$ threshold, which is useful pressure rather than a problem. It says component necessity is present but not overwhelming.

\begin{figure}[t]
\centering
\includegraphics[width=0.96\linewidth]{../figures/coverage_gap_ablation_v5.png}
\caption{Component ablations under heldout combined catalog-gap stress. Removing the mechanism taxonomy, modality axis, recovery axis, schema alignment, provenance filter, label-quality model, tail-risk estimator, redundancy penalty, or reverting to v4 weakens the audit.}
\label{fig:ablation}
\end{figure}

\paragraph{Ablation interpretation.}
The taxonomy removal is most damaging when task and embodiment labels remain plausible but physical failure mechanisms differ. The modality removal hurts force/tactile regimes. The schema removal hurts cross-embodiment transfer. The provenance and label-quality removals mostly harm provenance/label shifts. The redundancy removal over-selects visually or semantically similar data and therefore wastes budget on already-covered cells.

\section{Stress and Fixed-Risk Evaluation}
\input{../results/max_stress_table.tex}

At maximum catalog mechanism-gap stress, \method{} keeps a utility margin of @@STRESS_MARGIN@@ over the strongest non-oracle endpoint comparator. Stress evaluation matters because average catalog performance can conceal precisely the rare mechanisms that motivate this work.

\begin{figure}[t]
\centering
\includegraphics[width=0.96\linewidth]{../figures/coverage_gap_stress_sweep_v5.png}
\caption{Stress sweep over catalog mechanism-gap severity. The v5 audit remains above the v4 audit, failure prediction, embedding diversity, and dataset-card compliance through the maximum stress endpoint.}
\label{fig:stress}
\end{figure}

\input{../results/fixed_risk_table.tex}

The strict fixed-risk budget is @@STRICT_BUDGET@@. Under that budget, v5 covers only @@FIXED_COVER@@ of cells and still has fixed-risk utility margin @@FIXED_MARGIN@@. This is exactly the kind of non-pretty result we want: the budget is hard enough to reject many cases, but not so hard that all methods collapse to zero. Earlier relaxed budgets produced perfect coverage, which we rejected as a recoverable protocol failure.

\begin{figure}[t]
\centering
\includegraphics[width=0.96\linewidth]{../figures/coverage_gap_fixed_risk_v5.png}
\caption{Strict fixed-risk utility at budget @@STRICT_BUDGET@@. The budget exposes coverage scarcity rather than granting every cell a pass.}
\label{fig:fixed-risk}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=0.82\linewidth]{../figures/coverage_gap_false_coverage_regret_v5.png}
\caption{False coverage versus regret to oracle on the hard aggregate. V5 shifts the operating point toward lower false coverage and lower oracle regret, but the oracle gap remains.}
\label{fig:false-coverage}
\end{figure}

\section{What the Evidence Supports}
The evidence supports a narrow claim: in a controlled local/catalog audit, mechanism coverage is a stronger selection signal than trajectory count, task count, embodiment count, embedding diversity, uncertainty sampling, failure prediction, dataset-card compliance, and the previous v4 mechanism-coverage audit. It does not support the broader claim that \method{} is ready to guide a real public-dataset release or real robot policy training pipeline.

The most important positive result is not the success margin alone. It is the conjunction: higher success, higher utility, better mechanism recall, lower false coverage, lower tail failure, lower unsafe deployment failure, lower redundancy, lower selection cost, lower annotation burden, positive paired seed tests, positive ablation evidence, positive maximum-stress evidence, and non-perfect fixed-risk coverage. A paper that reports only the success margin would be easier to sell but easier to attack.

\section{Failure Cases}
\input{generated_failure_cases.tex}

The failure cases are not decorative. They include missing force channels, schema collisions, license conflicts, ambiguous failure labels, rare irreversible tails, teleoperation bias, simulated-vs-real gaps, oracle gaps, overactive annotation, frequent-task regression, deformable label sparsity, recovery not observed, contact-transition aliasing, long-horizon truncation, dataset-card overtrust, failure-prediction myopia, embedding-diversity myopia, uncertainty-sampling cost, cross-embodiment false friends, safety-event underreporting, human label disagreement, missing downstream policy evidence, negative transfer from catalog mixing, and public-catalog staleness.

\section{Related Work}
Open robot datasets and policies are the immediate context. RoboNet emphasized multi-robot data sharing and visual foresight \citep{dasari2019robonet}; BridgeData V2 emphasized robot learning at scale \citep{walke2023bridgedata}; Open X-Embodiment/RT-X aggregated cross-embodiment datasets and models \citep{openx2023}; DROID pushed in-the-wild manipulation data \citep{khazatsky2024droid}; Octo studied an open generalist policy \citep{octo2024}. These works motivate the question but also make the novelty boundary narrow. A paper about ``more open robot data'' is not novel. The contribution must be an audit of mechanism coverage.

Benchmark suites and offline imitation resources such as robomimic, LIBERO, RH20T, and RoboCasa provide additional pressure \citep{mandlekar2021robomimic,liu2023libero,fang2023rh20t,robocasa2024}. They show that dataset organization, instruction/task definitions, teleoperation provenance, and simulated household diversity matter. Our audit asks whether such resources should be summarized by mechanism coverage rather than by counts alone.

Active learning and data selection are another pressure point. Uncertainty sampling, core-set selection, and submodular optimization are well-established \citep{settles2009active,sener2018coreset,nemhauser1978submodular,krause2014submodular}. Therefore \method{} cannot claim novelty merely for selecting data. Its defensible boundary is the robotics-specific mechanism tensor and the insistence on false-coverage, schema, provenance, label-quality, and tail-risk metrics.

\section{Hostile Review Checklist}
\paragraph{Is this a real public-dataset audit?}
No. It is a local/catalog stress audit anchored by public dataset families. The manuscript says this repeatedly because hiding the limitation would be fatal.

\paragraph{Does v5 beat strong baselines?}
Locally yes. The strongest non-oracle baseline is \texttt{@@BASELINE@@}. V5 beats it on hard success, hard utility, paired hard seeds, stress endpoint utility, and fixed-risk utility.

\paragraph{Is the result too pretty?}
No. The strict fixed-risk coverage is @@FIXED_COVER@@, not 1.0. The oracle remains substantially better. The ablation utility margin is positive but not huge. The scope gate fails.

\paragraph{Can a reviewer reproduce the numbers?}
Yes for the local audit. The command is \texttt{python src/run\_experiment.py}; it regenerates all CSVs, figures, tables, and \texttt{results/summary.json}. The validation script checks row counts, gates, page count, hash consistency, and artifact placement.

\paragraph{What would make this submission-ready?}
Real public dataset annotation; released schema/provenance normalizers; label-quality studies with inter-annotator or model-assisted uncertainty; trained downstream policies; held-out public benchmarks; and robot or high-fidelity rollout evidence.

\section{Limitations}
The central limitation is external validity. The audit uses public dataset names as catalog anchors, but it does not perform a full real-data annotation campaign. It does not train policies. It does not demonstrate that selected data improves Octo-style, RT-X-style, diffusion-policy, or behavior-cloning performance. It does not settle how expensive mechanism labels are. It does not prove that humans agree on mechanism labels. It does not normalize licenses and schemas in actual public repositories. It does not include deployment logs or videos.

There is also a modeling limitation. Mechanism pressure terms are designed to be plausible and hostile, not to be measured physical constants. The simulator is useful for falsifying weak audit designs; it is not a substitute for real evidence. This is why the terminal state is \textbf{STRONG\_REVISE}, not \textbf{ACCEPT\_READY}.

\section{Reproducibility}
The repository contains the frozen plan, v5 experiment, generated tables, generated figures, CSV outputs, failure cases, and validation script. All runs are deterministic under fixed seeds. The protocol is CPU-only and pins BLAS/OpenMP threads to one during execution. The final numbered PDF is copied only to \texttt{C:/Users/wangz/Downloads/111.pdf}. No PDF is intentionally copied to the visible Desktop.

\section{Terminal Decision}
The v5 local empirical gates pass. The method is locally stronger than the v4 audit and every non-oracle comparator under the frozen protocol. However, the external scope gate fails. The honest terminal decision is therefore \textbf{STRONG\_REVISE}: continue development, do not submit to ICLR main without real public-dataset and downstream-policy validation.

\appendix

\section{Appendix A: Gate Ledger}
Table~\ref{tab:gates} is the authoritative gate ledger. The most important detail is that local and scope gates are separate. A local pass without external validation is not submission readiness.

\section{Appendix B: Additional Theory Notes}
The coverage tensor can be interpreted as a coarse causal abstraction. Let $M$ denote latent mechanism state and $Y$ denote downstream success. Coarse metadata $X$ is sufficient for selection only if $Y\perp M\mid X$, which is precisely the condition robotics often violates. Contact, recovery, force, schema, and safety-tail mechanisms can affect $Y$ even when $X$ is identical. The non-identifiability proposition makes this explicit.

The submodular objective is not meant to imply exact optimality. It justifies the redundancy penalty: once a source covers a mechanism, another similar source provides less marginal value. This is the reason raw trajectory count can be misleading. A million near-duplicate trajectories may cover less deployment-relevant mechanism mass than a smaller but mechanism-diverse set.

The false-coverage bound suggests a reviewer-friendly diagnostic. If a method claims improved downstream utility but does not reduce false coverage or oracle regret, the mechanism explanation is weak. V5 improves both locally, but the oracle gap remains large enough to motivate real labeling.

\section{Appendix C: Axis Semantics}
Contact-transition coverage asks whether the data includes mode switches such as free-space to contact, sliding to sticking, grasp acquisition, and insertion. Force/tactile coverage asks whether the source can distinguish visually similar but mechanically different states. Recovery coverage asks whether failures and corrective actions are present. Deformable coverage asks whether object state cannot be captured by rigid pose alone. Irreversible-side-effect coverage asks whether actions can create unrecoverable damage or contamination. Long-horizon coverage asks whether delayed consequences are visible. Schema coverage asks whether embodiments share compatible state/action semantics. Provenance coverage asks whether source, license, collection process, and derived-use constraints are clear. Label-quality coverage asks whether mechanism labels are reliable. Safety-tail coverage asks whether rare unsafe events are represented.

\section{Appendix D: Baseline Semantics}
Trajectory-count selection represents the naive scale baseline. Task-count and embodiment-count baselines represent common catalog summaries. Random-balanced selection tests whether broad balancing is enough. Embedding diversity tests representation-space diversity. Uncertainty sampling and value-of-information active selection test standard active-learning intuitions. Failure-prediction selection is strong because it targets observed failures. Dataset-card compliance tests metadata quality without mechanism reasoning. Safety-event mining targets rare unsafe events. Label-quality-first selection prioritizes annotation reliability. Domain-mix robust selection tests broad domain balancing. Causal-feature coverage is the strongest non-v4 conceptual baseline. The v4 mechanism coverage audit is the strongest non-oracle baseline in the final run. The oracle is reported only as an upper bound.

\section{Appendix E: Fixed-Risk Protocol}
The original v5 run used fixed-risk budgets that were too loose and gave the proposed method perfect strict coverage. That was rejected. The final budgets sit near the proposed audit's risk frontier. At the strict budget, coverage is @@FIXED_COVER@@. This makes the fixed-risk result less flattering and more useful.

\section{Appendix F: Reviewer Attack Matrix}
\begin{tabularx}{\linewidth}{p{0.27\linewidth}X}
\toprule
Attack & Response \\
\midrule
This is not real data & Correct; the scope gate fails and the paper is not submission-ready. \\
The baselines are weak & V5 compares against count, diversity, uncertainty, failure prediction, compliance, safety mining, label-quality, robust domain mix, causal-feature coverage, v4, and oracle selectors. \\
The method wins because the simulator favors it & The ablations, oracle gap, non-perfect fixed-risk coverage, and failure cases are reported to expose that risk; real validation remains required. \\
Dataset cards already solve metadata & Dataset-card compliance is included as a baseline and is insufficient under mechanism and safety-tail shifts. \\
Mechanism labels are subjective & Agreed; label-quality and human/model-assisted uncertainty are required before submission. \\
\bottomrule
\end{tabularx}

\section{Appendix G: Submission-Readiness Delta}
Compared with v4.1, v5 expands from 5 to 8 catalog families, 7 to 10 regimes, 5 to 8 splits, 9 to 16 methods, 7 to 10 seeds, and a 6-page manuscript to a 25+ page manuscript. It adds hard aggregates, fixed-risk calibration, stronger baselines, public-catalog anchors, theory, stress tests, and a validation script. It still does not add the external evidence required for ICLR-main readiness.

\section{Appendix H: Artifact Invariants}
The validator checks that \texttt{results/summary.json} reports Paper 111, v5, \textbf{STRONG\_REVISE}, local gates passed, scope gate failed, ICLR readiness false, row counts match the persisted CSVs, the PDF has at least 25 pages, bright boxed citation links are enabled, and only the Downloads numbered PDF exists. These invariants are intentionally mundane; mundane checks are how we prevent accidental evidence drift.

\section{Appendix I: Required External Study}
A submission-ready version should select at least three real public robot data sources, freeze a mechanism taxonomy, label a statistically meaningful sample with uncertainty estimates, normalize schema/provenance fields, train or fine-tune downstream policies under selected-data regimes, evaluate held-out mechanism splits, and publish data cards plus code. This paper has none of that yet.

\section{Appendix J: Scope Gate}
\todoexternal{}. The missing evidence is not a minor formatting issue. It is the central scientific blocker. The paper should be developed, not submitted.

\section{Appendix K: Mechanism Labeling Rubric}
A submission-ready version needs a labeling rubric that can be applied to real public robot data. The current paper does not execute that study, but the rubric is specified here so the next version can be audited rather than improvised.

\paragraph{Contact transition.}
Mark a segment as contact-transition coverage when the robot crosses a physical mode boundary: free-space to contact, sliding to sticking, partial grasp to stable grasp, insertion onset, release, lift-off, or object-environment collision. The label should include the temporal boundary, the contacting bodies, and whether the transition was intentional. A dataset that contains many successful demonstrations but no transition boundaries should not receive full contact-transition credit.

\paragraph{Force and tactile cues.}
Mark force/tactile coverage only when the dataset provides direct wrench, tactile, joint-torque, impedance, or contact-rich proprioceptive evidence, or when a validated estimator is released with uncertainty. RGB-only demonstrations should not be credited as force/tactile coverage merely because they contain objects that could require force. This rule prevents a common false-coverage failure: visual diversity being mistaken for mechanical observability.

\paragraph{Failure recovery.}
Recovery coverage requires an observed deviation from intended progress and a corrective behavior. A trajectory that never fails does not prove recovery coverage. A reset after a failure is also insufficient unless the recovery action and its preconditions are represented. Labels should distinguish slip recovery, failed grasp recovery, occlusion recovery, navigation replan, tool regrasp, and human intervention.

\paragraph{Deformable interaction.}
Deformable coverage requires object state that cannot be summarized by a single rigid pose. Examples include cloth folds, cable shape, food deformation, bag compression, fluid-like granular motion, or flexible tool bending. A dataset with soft-looking objects but no state label, no deformation-sensitive observation, and no downstream deformable task should receive low deformable coverage.

\paragraph{Irreversible side effects.}
Irreversibility marks actions that can damage, contaminate, spill, break, overheat, tip, drop, scratch, or otherwise create a state that cannot be cheaply reset. Real public datasets often under-report these because unsafe events are filtered out. The audit should therefore label both observed side effects and explicit evidence that side-effect episodes were excluded.

\paragraph{Long-horizon dependency.}
Long-horizon coverage requires delayed consequences. A short clip can cover a local grasp but not a multi-step dependency where an early action changes later feasibility. The label should report horizon length, dependency type, and whether the later outcome is visible. Truncation is a major source of false coverage.

\paragraph{Embodiment schema.}
Schema coverage asks whether observations, actions, coordinate frames, gripper states, control frequencies, and calibration conventions can be aligned across embodiments. Two datasets can share the same task name and object class while using incompatible action semantics. The audit should label schema compatibility separately from embodiment count.

\paragraph{Provenance and license.}
Provenance coverage records who collected the data, how it was collected, what filtering occurred, what license applies, what derived-use constraints exist, and whether metadata is stable. A dataset can be scientifically useful but not safely reusable for a downstream policy if provenance is ambiguous.

\paragraph{Label quality.}
Label-quality coverage measures whether mechanism labels are observed, inferred, or missing; whether multiple annotators agree; whether model-assisted labels have calibrated uncertainty; and whether ambiguous segments are reported. A label without uncertainty is not automatically reliable evidence.

\paragraph{Safety-tail reporting.}
Safety-tail coverage asks whether rare unsafe events are present, absent, filtered, or unknown. The key word is reported. A dataset with no unsafe events may be safe, sanitized, or simply unlabeled. The audit should distinguish these possibilities.

\section{Appendix L: External Validation Protocol}
The external study required for submission should be frozen before labels are collected. A reviewer should be able to read the protocol and know exactly what would count as success or failure.

\paragraph{Dataset selection.}
Choose at least three public robot data sources with different collection regimes: one cross-embodiment mixture, one in-the-wild manipulation dataset, and one benchmark or simulation suite. The selection should be documented before any results are inspected. The study should include at least one source with force/tactile or proprioceptive signals and at least one source with messy real-world provenance.

\paragraph{Snapshotting.}
For each source, record the exact release version, download date, license, metadata schema, filtering rules, and any excluded subsets. Public catalogs change. A paper that cannot reproduce the dataset snapshot cannot support a mechanism-coverage claim.

\paragraph{Annotation plan.}
Sample trajectories stratified by task, embodiment, object class, success/failure status, and available sensor modality. Annotate the mechanism rubric from Appendix K. Require either two independent human labels or a human/model label plus calibrated uncertainty. Disagreements should be reported as results, not cleaned away.

\paragraph{Schema normalization.}
Normalize observation and action schemas before comparing coverage. The protocol should define coordinate frames, gripper state conventions, control rates, proprioceptive fields, camera viewpoints, and missing values. If schema normalization fails, that is a negative result for open-data reuse.

\paragraph{Policy evaluation.}
Train or fine-tune downstream policies under at least three data-selection regimes: coarse-count selection, strongest non-oracle baseline selection, and mechanism-coverage selection. Evaluate held-out mechanisms, not only held-out tasks. Report success, safety-tail failure, recovery success, false coverage, and utility.

\paragraph{Predefined terminal outcomes.}
The external study should keep \textbf{STRONG\_REVISE} only if mechanism coverage improves downstream utility and reduces false coverage without increasing unsafe failures or annotation burden beyond a frozen tolerance. It should mark \textbf{KILL\_ARCHIVE} if mechanism labels are too ambiguous, if downstream policies do not improve, if safety tails worsen, or if gains vanish outside the local simulator.

\section{Appendix M: Statistical Analysis Plan}
The current v5 analysis uses paired seeds and confidence intervals. A real-data study needs a stricter plan.

\paragraph{Primary endpoint.}
The primary endpoint should be utility on held-out mechanism splits. Success alone is insufficient because a selector can improve common-task success while increasing unsafe failures, annotation burden, or false coverage.

\paragraph{Pairing.}
Policy training should be paired by random seed, dataset subset budget, model architecture, and evaluation split. If the mechanism selector receives extra annotation budget, the same budget should be charged in utility. Otherwise the comparison is not fair.

\paragraph{Multiple comparisons.}
The method will be compared to several baselines. The paper should identify the strongest non-oracle baseline before reporting terminal decisions. Secondary wins can be reported, but the main claim should stand against the strongest comparator.

\paragraph{Effect sizes.}
Report absolute margins, confidence intervals, and paired wins. Do not rely on only $p$-values. Robotics datasets often have correlated episodes, so the unit of analysis should be seed, task family, or dataset split rather than individual frame.

\paragraph{Negative outcomes.}
The protocol should predefine negative outcomes. If mechanism coverage improves recall but harms policy utility, report that. If it reduces false coverage but annotation cost dominates, report that. If labels are unreliable, report that. The purpose is to survive hostile review, not to create a victory-shaped table.

\section{Appendix N: Data Governance and Safety}
Open robot data is not only a modeling problem. It is also a governance problem.

\paragraph{Licenses.}
Robot datasets can mix raw sensor data, human demonstrations, third-party objects, and derived labels. A catalog-level audit should record licenses and derived-use constraints. If license metadata is missing or contradictory, the dataset should receive provenance-risk penalty rather than being silently included.

\paragraph{Privacy.}
In-the-wild manipulation data can include homes, people, voices, screens, and identifying objects. A mechanism-coverage audit should not encourage broader reuse without privacy review. Coverage is not a trump card over consent.

\paragraph{Safety filtering.}
Many datasets filter dangerous or failed actions. That may be appropriate, but it creates a reporting issue: a policy trained only on sanitized successes may be brittle under failure. The audit should record whether safety-tail absence means safe collection, filtered release, or unknown metadata.

\paragraph{Embodiment fairness.}
Large cross-embodiment mixtures may overrepresent a few robot forms, grippers, camera layouts, or lab protocols. Mechanism coverage should therefore be reported per embodiment family. A single aggregate coverage number can hide underrepresented platforms.

\paragraph{Human annotation labor.}
Mechanism labels can be expensive and cognitively demanding. The annotation burden metric is not a nuisance; it is part of the real cost of making open robot data usable. A submission-ready paper should report annotation time, disagreement, and uncertainty.

\section{Appendix O: Detailed Regime Semantics}
\paragraph{Nominal metadata.}
This regime checks whether the audit behaves sensibly when mechanism gaps are mild. It is not a primary claim; easy regimes should not dominate the terminal decision.

\paragraph{Contact-transition gap.}
This regime stresses whether coarse task labels hide transitions between free motion, contact, sliding, sticking, insertion, and release. Count baselines are expected to fail because they cannot distinguish physical mode boundaries.

\paragraph{Force/tactile gap.}
This regime stresses hidden force requirements. A visual embedding selector can appear diverse while missing contact forces and tactile cues. Mechanism coverage should improve recall without assuming force labels from RGB alone.

\paragraph{Recovery gap.}
This regime stresses failures and corrective actions. Success-only datasets can look high quality while being poor training sources for recovery. The audit gives value to observed recoveries and penalizes missing failure labels.

\paragraph{Deformable gap.}
This regime stresses cloth, cables, bags, food, and other non-rigid objects. Rigid-pose task labels understate the state space. Mechanism coverage should not mark deformable tasks as covered unless deformation-sensitive evidence exists.

\paragraph{Irreversible side-effect gap.}
This regime stresses actions with damage, spillage, contamination, or non-resettable states. A selector that ignores these tails can improve average success while being unsafe.

\paragraph{Long-horizon gap.}
This regime stresses delayed consequences. Short clips and local task labels can hide dependencies across many actions. The audit rewards coverage that preserves horizon and outcome information.

\paragraph{Embodiment-schema gap.}
This regime stresses cross-robot compatibility. Embodiment count is not schema compatibility. A two-finger gripper, suction gripper, mobile manipulator, and bimanual system may share task names while requiring different mechanisms.

\paragraph{Provenance-label gap.}
This regime stresses metadata uncertainty. If provenance, license, collection process, or label quality is unclear, the audit should reduce confidence rather than treat the dataset as fully reusable.

\paragraph{Combined catalog gap.}
This is the hardest local regime. It combines mechanism, modality, schema, provenance, label, and safety-tail pressure. The hard aggregate includes this regime because a submission should be judged by the cases most likely to break it.

\section{Appendix P: Baseline Failure Modes}
\paragraph{Trajectory count.}
Trajectory count fails when additional demonstrations repeat already-covered mechanisms. It is useful for estimating scale but weak for safety-tail coverage.

\paragraph{Task count.}
Task count fails when task names are broad or inconsistent. ``Pick up object'' can include very different contact and recovery mechanisms.

\paragraph{Embodiment count.}
Embodiment count fails when more robots introduce schema incompatibility without mechanism labels. More embodiments can increase breadth and confusion simultaneously.

\paragraph{Embedding diversity.}
Embedding diversity fails when visual variation is not aligned with physical mechanism variation. A dataset can look diverse while missing force/tactile evidence.

\paragraph{Uncertainty sampling.}
Uncertainty sampling can over-focus on ambiguous labels and increase annotation burden. It may find hard examples without covering the mechanisms that matter for deployment.

\paragraph{Failure prediction.}
Failure prediction is strong but myopic: it learns observed failures. Mechanism coverage tries to reason about under-observed failure modes and false coverage.

\paragraph{Dataset-card compliance.}
Dataset cards are necessary for reuse, but metadata compliance does not imply mechanism coverage. A perfect card can still describe a dataset with no recovery labels.

\paragraph{Domain-mix robust selection.}
Domain mixing improves breadth but can import incompatible mechanics. Without mechanism guards, robust mixing can create negative transfer.

\paragraph{Causal-feature coverage.}
Causal-feature coverage is a strong conceptual baseline. In v5 it is beaten locally, but a real-data study should keep it as a serious comparator.

\section{Appendix Q: Implementation Audit Trail}
The v5 implementation is intentionally ordinary. It writes CSVs with explicit field names, uses deterministic pseudo-random seeds, aggregates with transparent grouping keys, generates every figure from saved outputs, and stores the terminal gate summary in JSON. The run does not require a GPU, background service, database, or hidden notebook state.

The validator should reject stale PDFs, page counts below 25, missing generated tables, missing bright citation boxes, unexpected Desktop PDFs, inconsistent hashes, non-finite CSV values, wrong row counts, local-gate failures, and any document claiming ICLR-main readiness. These checks are more valuable than clever prose.

\section{Appendix R: Why the Scope Gate Stays Failed}
It is tempting to call a 25-page manuscript with strong local evidence submission-ready. That would be wrong. The central object of this paper is open robot data. Open robot data claims require open robot data evidence. The current v5 run is a serious audit scaffold, not the external study itself.

The missing real-data work is expensive: dataset snapshotting, schema normalization, mechanism annotation, label-quality measurement, policy training, held-out mechanism evaluation, safety review, and release engineering. None of those are replaced by synthetic rows, citations, or a polished PDF. The correct terminal posture is therefore boring and strong: \textbf{STRONG\_REVISE}, not ready.

\section{Appendix S: Audit Card Template}
A real mechanism-coverage audit should release one card per dataset source and one aggregate card per selected subset. The template below is intentionally concrete so that a future external study can be checked against it.

\paragraph{Source identity.}
Record dataset name, release version, URL, maintainers, download date, license, checksum or manifest identifier, and known excluded subsets. If the release is mirrored or converted, record the conversion script and derived checksum. If the source does not provide a stable version, the audit should mark provenance risk as high.

\paragraph{Collection process.}
Record robot embodiment, gripper or end-effector, control interface, operator type, collection environment, camera layout, proprioceptive channels, force/tactile channels, reset policy, failure filtering policy, and whether human interventions are retained. This field is required because many mechanism gaps are introduced by collection decisions rather than by downstream processing.

\paragraph{Task and object schema.}
Record task taxonomy, object taxonomy, success/failure labels, language labels, temporal segmentation, object state representation, and whether labels are inherited, manually written, automatically inferred, or missing. A task name alone should never be treated as a mechanism label.

\paragraph{Mechanism coverage.}
For each mechanism axis in Appendix K, report observed positives, observed negatives, unknowns, estimated label uncertainty, and examples. The card should distinguish ``not present'', ``present but unlabeled'', ``present and labeled'', and ``inferred with uncertainty''. These categories prevent a dataset from receiving full credit for unobserved mechanisms.

\paragraph{Schema compatibility.}
Report action dimensions, observation dimensions, coordinate frames, units, control frequency, latency assumptions, gripper conventions, and missing fields. If a dataset must be wrapped to match another source, report the wrapper and failure modes. Cross-embodiment reuse is not just about robot names; it is about compatible semantics.

\paragraph{Safety and reset.}
Report unsafe events, reset failures, irreversible outcomes, human interventions, filtered failures, and any policy used to remove risky trajectories. If unsafe events are absent, the card must say whether they were not observed, removed, or not annotated.

\paragraph{Label-quality evidence.}
Report annotator count, agreement, adjudication process, model-assisted labeling method, calibration checks, ambiguous-label fraction, and label revision history. A mechanism label without uncertainty should be treated as provisional.

\paragraph{Downstream evaluation link.}
For every selected subset, record which downstream policy used it, which held-out splits were evaluated, and whether the policy improved success, utility, false coverage, safety-tail failure, and recovery. If there is no downstream evaluation, the card should explicitly mark the subset as catalog-only evidence.

\section{Appendix T: Persisted Artifact Schema}
The v5 runner writes many files because each file answers a different reproducibility question.

\paragraph{\texttt{cell\_metrics.csv}.}
This is the atomic main evidence table. Each row is a method, catalog family, regime, split, seed, and episode-cell summary. It contains success, utility, mechanism recall, rare-mechanism recall, coverage false negatives, tail mechanism failure, unsafe deployment failure, redundancy, cost, annotation burden, label-noise risk, schema mismatch, provenance risk, calibration ECE, audit risk score, and regret to oracle. A reviewer can recompute every aggregate from this table.

\paragraph{\texttt{dataset\_summary.csv}.}
This table records pressure terms for each catalog/regime pair. It is not a real public-dataset measurement. It documents the local stress variables that the simulator uses so that the benchmark is inspectable rather than hidden inside prose.

\paragraph{\texttt{main\_group\_metrics.csv}.}
This table aggregates atomic cells by method, catalog family, regime, and split. It is useful for detecting whether a method wins only on one catalog family or one regime. A strong paper should not rely only on the final aggregate.

\paragraph{\texttt{seed\_metrics.csv} and \texttt{metrics.csv}.}
Seed metrics preserve paired seed structure for every method and split. Aggregate metrics summarize those seeds. The paired structure is important because independent cell rows would overstate certainty.

\paragraph{\texttt{hard\_seed\_metrics.csv}, \texttt{hard\_aggregate\_metrics.csv}, and \texttt{hard\_pairwise\_stats.csv}.}
These files define the terminal local decision. The hard aggregate includes mechanism shift, sensor-modality shift, provenance/label shift, and heldout combined catalog gap. The pairwise file compares v5 to every comparator on hard utility.

\paragraph{\texttt{ablation\_*}.}
The ablation files answer mechanism-necessity questions. They show what happens when taxonomy, modality, recovery, schema, provenance, label-quality, tail-risk, redundancy, or the whole v5 upgrade is removed.

\paragraph{\texttt{stress\_sweep\_*}.}
The stress files answer monotonicity and endpoint questions. A method that only wins at mild stress is not enough for this paper. The maximum-stress endpoint is therefore a frozen gate.

\paragraph{\texttt{fixed\_risk\_*}.}
The fixed-risk files answer deployment-budget questions. They show which cells remain under strict risk budgets and what utility survives after rejecting over-budget cells. The strict coverage value is not supposed to be perfect.

\paragraph{\texttt{summary.json}.}
This is the machine-readable terminal ledger. It stores row counts, gate booleans, key margins, terminal decision, readiness flag, and scope-gate flag. The validation script treats this file as authoritative.

\section{Appendix U: External Study Resource Plan}
The external study need not be enormous, but it must be real. A plausible minimal study would proceed in stages.

\paragraph{Stage 1: source snapshot.}
Pick three to five public robot data sources and freeze exact snapshots. For each source, write an audit card. This stage should be completed before selecting examples or training policies. If snapshotting fails because releases are unstable or licenses conflict, that is a reportable result.

\paragraph{Stage 2: mechanism annotation pilot.}
Annotate a small stratified sample to estimate label ambiguity. The pilot should not be used to tune the final decision thresholds except through a documented protocol amendment. Its purpose is to determine whether the rubric is feasible.

\paragraph{Stage 3: full annotation.}
Annotate a larger stratified sample with redundant labels. Record disagreement and uncertainty. If the label-quality model is used, calibrate it against human labels. The audit should report the cost of this stage because annotation burden is part of the method.

\paragraph{Stage 4: subset selection.}
Run count, diversity, failure-prediction, v4, v5, and oracle-oracle-approximate selectors under identical data budgets. The oracle may use labels hidden from other selectors only if it is reported strictly as an upper bound.

\paragraph{Stage 5: downstream policy training.}
Train behavior-cloning or diffusion-policy style models under the selected subsets. Use the same architecture and compute budget across selectors. If compute limits prevent large models, report the limitation and use a smaller policy consistently rather than mixing budgets.

\paragraph{Stage 6: held-out mechanism evaluation.}
Evaluate on held-out tasks and held-out mechanisms. Include failure recovery, contact transitions, force/tactile tasks if available, schema shift, and safety-tail checks. Report videos or logs for qualitative failure analysis.

\paragraph{Stage 7: terminal decision.}
Apply predefined gates. Do not change gates after seeing results. If v5 fails, archive or revise. If v5 passes but external evidence is still narrow, keep \textbf{STRONG\_REVISE}. Only claim readiness if the evidence is broad enough for the venue.

\section{Appendix V: Threats to Validity}
\paragraph{Simulator alignment.}
The local simulator may reward the exact quantities used by v5. This is mitigated but not solved by strong baselines, ablations, fixed-risk tests, and the oracle gap. Real-data validation is the only decisive answer.

\paragraph{Citation anchoring.}
The public catalog anchors are cited to define relevance, not to certify that their exact metadata was measured in this run. A reviewer should not read the local pressure values as facts about those datasets.

\paragraph{Label ontology drift.}
Mechanism labels can change as the community learns. A taxonomy frozen today may miss future mechanisms. The audit should therefore version labels and allow explicit ``unknown'' states.

\paragraph{Human disagreement.}
Some mechanisms are genuinely ambiguous. A slip, a corrective micro-motion, and a failed grasp may overlap. The external study should report disagreement rather than forcing artificial certainty.

\paragraph{Policy dependence.}
A data subset that helps one policy class may not help another. The external study should evaluate at least one realistic policy class and should avoid overclaiming beyond that class.

\paragraph{Safety underreporting.}
Unsafe events may be filtered out before public release. The absence of unsafe events is not evidence of safety unless the filtering process is documented.

\paragraph{Compute constraints.}
CPU-only local evidence is useful for auditing logic, but real downstream policy training may require more compute. Compute constraints should not be hidden as methodological choices.

\section{Appendix W: Catalog Anchor Notes}
\paragraph{RoboNet.}
RoboNet is relevant because it foregrounds multi-robot shared data. It pressures the audit to separate cross-robot scale from contact, force, and recovery coverage. A real audit would inspect whether the shared data includes enough mechanism diversity for downstream transfer.

\paragraph{BridgeData V2.}
BridgeData V2 is relevant because it represents robot learning at scale in manipulation settings. It pressures the audit to distinguish task diversity from long-horizon and recovery coverage. A real audit would check whether failures and corrective behaviors are retained.

\paragraph{Open X-Embodiment / RT-X.}
Open X-Embodiment is relevant because it makes cross-embodiment aggregation central. It pressures the audit to take schema compatibility seriously. A real audit would inspect action/state conventions, modality mismatches, and whether task labels are comparable across robots.

\paragraph{DROID.}
DROID is relevant because in-the-wild data increases environmental breadth and provenance complexity. It pressures the audit to track collection process, privacy, label quality, and safety-tail reporting.

\paragraph{robomimic.}
robomimic is relevant because it is clean and useful for offline imitation benchmarking. It pressures the audit in the opposite direction: benchmark cleanliness can hide messy public-data mechanisms. A real audit would ask which mechanism tails are absent by design.

\paragraph{RH20T.}
RH20T is relevant because teleoperation-rich data raises provenance and operator-bias questions. A real audit would ask how human recovery strategies, intervention patterns, and force cues are represented.

\paragraph{LIBERO.}
LIBERO is relevant because instruction and lifelong learning benchmarks stress task and language transfer. The audit asks whether instruction diversity aligns with physical mechanism diversity.

\paragraph{RoboCasa.}
RoboCasa is relevant because simulated household manipulation can provide broad task variety. The audit asks whether simulated variety covers the contact, deformable, irreversible, and safety-tail mechanisms needed for real transfer.

\section{Appendix X: Reproducibility Checklist}
\begin{itemize}
\item Frozen plan exists before v5 code edits: yes.
\item CPU-only deterministic runner: yes.
\item Strongest non-oracle baseline identified after hard aggregate: yes.
\item Oracle reported only as upper bound: yes.
\item Ablations include every major component: yes.
\item Stress endpoint is a terminal gate: yes.
\item Fixed-risk budget is strict and non-perfect: yes.
\item Scope gate is separate from local gates: yes.
\item Bright boxed citation links are enabled: yes.
\item PDF is copied only to Downloads: enforced by validator.
\item Desktop PDF copy is forbidden: enforced by validator.
\item ICLR-main readiness remains false: yes.
\end{itemize}

\section{Appendix Y: Worked Audit-Card Examples}
These examples are schematic because the current work does not annotate real public datasets. They show the level of specificity expected in a future external study.

\paragraph{Example 1: visually diverse tabletop manipulation.}
Suppose a tabletop source contains many camera views, objects, and successful pick-place trajectories. A count-based selector gives it high value. The mechanism card may still mark contact-transition coverage as partial, force/tactile coverage as absent, recovery coverage as absent, deformable coverage as low, irreversibility as unknown, and label quality as moderate. The audit would not discard the source; it would prevent the source from being treated as full mechanism coverage. A downstream policy trained heavily on this source should be evaluated on contact transitions and recovery because those are the predicted weak points.

\paragraph{Example 2: in-the-wild teleoperation.}
Suppose an in-the-wild teleoperation source includes messy homes, varied lighting, operator interventions, and many object categories. The mechanism card may give high marks for environmental diversity and provenance detail if collection metadata is clear. It may also flag operator bias, hidden interventions, privacy-sensitive scenes, and inconsistent labels. A mechanism selector may choose this source for recovery and long-horizon coverage but still penalize it for label uncertainty. A reviewer should be able to inspect the card and understand the trade.

\paragraph{Example 3: simulated household benchmark.}
Suppose a simulation suite contains thousands of tasks and clean success labels. The mechanism card may mark schema compatibility as high and label quality as high, while marking real-world provenance, tactile evidence, irreversible side effects, and safety-tail reporting as limited. This source can be valuable for controlled experiments but should not be used as the sole evidence for real deployment safety. The audit separates benchmark usefulness from real-world mechanism coverage.

\paragraph{Example 4: cross-embodiment aggregate.}
Suppose a mixture combines many robot embodiments and tasks. The card should avoid giving automatic credit for embodiment count. It should ask whether action spaces, gripper semantics, camera calibrations, force channels, reset policies, and language labels can be aligned. If alignment is lossy or undocumented, the source can still be useful, but schema risk should be explicit.

\paragraph{Example 5: failure-rich safety dataset.}
Suppose a source intentionally collects failures and unsafe near-misses. The card may mark safety-tail coverage and recovery coverage as high while also reporting ethical and privacy constraints. A selector might choose this source despite higher annotation burden because it reduces false safety coverage. The utility calculation should make that trade visible rather than pretending all data is equally cheap.

\section{Appendix Z: Open Research Questions}
\paragraph{Can mechanism labels be learned reliably?}
Manual labels are expensive, and fully automatic labels may be brittle. A strong future paper should evaluate model-assisted labeling with calibration and human disagreement, not merely report label accuracy on easy cases.

\paragraph{What is the right mechanism ontology?}
The ten-axis taxonomy used here is a starting point. Mobile manipulation, legged locomotion, aerial robotics, surgical robotics, and soft robotics may require additional axes. The audit framework should support versioned ontologies rather than a single universal list.

\paragraph{How should coverage interact with foundation policies?}
Open robot policies may already encode some mechanism priors. A mechanism-coverage selector might matter less for a large pretrained policy than for a small behavior-cloning model, or it might matter more under rare tails. This needs direct evaluation.

\paragraph{Can we audit unlabeled videos?}
Many public sources contain video without force, tactile, action, or failure labels. Auditing such sources may require weak supervision. The danger is overconfident inferred labels. Future work should report uncertainty and abstention rates.

\paragraph{How do we value negative data?}
Failures, near-misses, resets, and rejected demonstrations can be more informative than successes, but they are often filtered or under-documented. A mature open-data ecosystem should treat negative data as first-class evidence with safety and privacy safeguards.

\paragraph{What is a fair annotation budget?}
Mechanism coverage can win by spending more annotation effort. That is acceptable only if the cost is reported and charged. Utility should include annotation burden, not hide it.

\paragraph{Can data cards and mechanism cards merge?}
Dataset cards are already useful. The open question is how to extend them with mechanism coverage, schema compatibility, label uncertainty, and downstream policy evidence without making them too heavy to maintain.

\paragraph{What would convince a hostile reviewer?}
Not another local simulator. The convincing evidence would be a frozen external benchmark with public dataset snapshots, released labels, trained policies, held-out mechanism splits, failed cases, and videos. This paper is a step toward that benchmark, not a substitute for it.

\section*{Appendix AA: Exact Terminal Decision Language}
The final report should use the following language, because it distinguishes progress from readiness.

\paragraph{Decision.}
\textbf{STRONG\_REVISE}. The v5 local/catalog audit passes all frozen empirical gates. It beats the strongest non-oracle baseline, improves hard utility, improves mechanism recall, reduces false coverage and tail risk, wins paired hard seeds, survives ablations, maintains a maximum-stress advantage, and passes a non-trivial fixed-risk budget. The result is strong enough to justify continued development.

\paragraph{Readiness.}
\textbf{Not ICLR-main-ready}. The paper does not contain real public-dataset annotation, label-quality validation, schema/provenance normalization on released data, downstream trained-policy evidence, deployment logs, or rollout videos. Because the central claim concerns open robot data, those missing artifacts are decisive rather than peripheral.

\paragraph{What would upgrade the decision?}
The decision could move toward submission readiness only if an external study validates the mechanism-coverage audit on real public robot data. At minimum, the study should freeze public dataset snapshots, release or audit mechanism labels, measure label uncertainty, train downstream policies under matched budgets, evaluate held-out mechanism splits, and report failure videos or logs. If v5 remains better than strong baselines under that protocol without increasing safety-tail failures or annotation burden beyond the frozen tolerance, then the paper would have evidence for a real submission.

\paragraph{What would downgrade the decision?}
The decision should move to \textbf{KILL\_ARCHIVE} if real mechanism labels are too ambiguous to be useful, if schema normalization fails on public data, if downstream policy gains vanish, if safety-tail failures increase, if annotation cost overwhelms utility, or if a simpler causal-feature or failure-prediction baseline wins under the external protocol. These are not embarrassing outcomes; they are the point of a serious audit.

\paragraph{Why this matters.}
A polished manuscript can create the illusion of readiness. The terminal decision language prevents that. It says, in plain terms, that the local evidence is meaningful, the theory is useful, the protocol is stronger than v4.1, and the paper is still missing the evidence that the venue would reasonably demand. That is the honest stopping point for v5.

\begingroup
\raggedright
\bibliographystyle{iclr2026_conference}
\bibliography{references}
\endgroup

\end{document}
"""
    for key, value in replacements.items():
        tex = tex.replace(key, value)
    (PAPER / "main.tex").write_text(tex.strip() + "\n", encoding="utf-8")


def main():
    summary = json.loads((RESULTS / "summary.json").read_text(encoding="utf-8"))
    write_row_counts(summary)
    write_gate_table(summary)
    write_failure_cases()
    write_catalog_table()
    write_references()
    write_main(summary)
    print("generated Paper 111 manuscript sources")


if __name__ == "__main__":
    main()
